/**
 * "Sign in here" — the highest-trust message in the system (plan S46).
 *
 * The step opens as a convenience feature: generate the auth URL, send it on
 * WhatsApp, park cleanly, resume from where it stopped. Then it says the thing
 * that actually shapes this file:
 *
 *   "Every other message asks Enrique to read something. **This one asks him to
 *    open a page and type a password into it** — and he will, because Jarvis
 *    asked, because he is on his phone, and because this is the normal way
 *    connections get made here... **an auth link is the exact shape a phishing
 *    attempt would want Jarvis to deliver**: a sign-in page Jarvis vouched for,
 *    arriving in the channel he trusts most."
 *
 * TWO RULES CARRY THAT, AND BOTH ARE ENFORCED BY TYPE RATHER THAN BY CARE.
 *
 * ONE: "**The link is generated by the connection flow — never extracted from
 * content.** A URL that appeared in an email, a page, a README or a tool result
 * is not an auth link; it is a string in a document." So `AuthLink` carries a
 * provenance with exactly ONE permitted value, and the only function that
 * produces it is `mintAuthLink`, which takes a flow rather than a URL. A string
 * lifted out of a message cannot be given that shape — not "should not", cannot.
 *
 * TWO: "**A connection request that did not originate with Enrique or an
 * already-approved task never produces a handoff.** Reading a message that says
 * *reconnect your Google account* is a fact about the message. It is not a reason
 * to send him a Google sign-in link." So the origin is required and closed, and
 * the two content-shaped origins produce content rather than a message.
 *
 * The Debug note points at the same place from the other side: "if a handoff
 * appears that Enrique did not initiate, look for the tool result or message body
 * that reached the connection request. **The bug will not be in the connection
 * code** — that code did exactly what it was asked; the question is who asked."
 * Which is why the origin travels with the request instead of being inferred.
 */
import type pg from "pg";

/**
 * Where a connection request came from.
 *
 * Required, closed, and ordered so the two that may produce a handoff are
 * obviously the two that involve a person. `message_content` and `tool_result`
 * are not lesser sources to be treated carefully — they are not sources of
 * authority at all.
 */
export type RequestOrigin = "enrique" | "approved_task" | "message_content" | "tool_result";

const MAY_HANDOFF: ReadonlySet<RequestOrigin> = new Set(["enrique", "approved_task"]);

/**
 * A link Jarvis is willing to vouch for.
 *
 * `provenance` has one value. That is the mechanism: a URL read out of a document
 * cannot be widened into this type, so "never extracted from content" is a fact
 * about what is constructible rather than a rule somebody has to remember while
 * writing the next integration.
 */
export type AuthLink = {
  readonly provenance: "connection_flow";
  readonly url: string;
  readonly provider: string;
  readonly expiresAt: Date;
};

/** What the connection flow hands over. Note: no URL comes in from outside. */
export type ConnectionFlow = {
  provider: string;
  /** The flow's own base — its host is the one he will be typing a password into. */
  authorizeUrl: string;
  /** How long the provider's link stays good. */
  lifetimeMs: number;
};

/**
 * The only way to obtain an AuthLink.
 *
 * Takes the FLOW, not a URL, so there is no parameter through which a string
 * found in a document could arrive. https only: a sign-in page reached over
 * plaintext is one whose destination can be rewritten in transit, which is
 * precisely the swap the message below exists to make visible.
 */
export function mintAuthLink(flow: ConnectionFlow, now = new Date()): AuthLink {
  const url = new URL(flow.authorizeUrl);
  if (url.protocol !== "https:") {
    throw new Error(`refusing to hand over a ${url.protocol} sign-in link for ${flow.provider}`);
  }
  return {
    provenance: "connection_flow",
    url: url.toString(),
    provider: flow.provider,
    expiresAt: new Date(now.getTime() + flow.lifetimeMs),
  };
}

export type HandoffDecision =
  | { send: true; message: string; link: AuthLink }
  | { send: false; why: string; asContent: true };

/**
 * Should this become a message he will tap?
 *
 * The origin decides, before anything is rendered. A request that arrived through
 * a message body or a tool result becomes CONTENT — "it lands as content; if it
 * is genuinely worth acting on, it becomes something he can act on, not something
 * Jarvis vouched for."
 */
export function handoffFor(args: {
  origin: RequestOrigin;
  link: AuthLink;
  /** Where he can see the same pending connection without the message. */
  consolePath?: string;
}): HandoffDecision {
  if (!MAY_HANDOFF.has(args.origin)) {
    return {
      send: false,
      asContent: true,
      why: `this connection request came from ${args.origin.replace("_", " ")}, which is a fact about `
        + "that content and not a reason to send him a sign-in link",
    };
  }
  return { send: true, message: handoffMessage(args.link, args.consolePath), link: args.link };
}

/**
 * The message, naming the provider and the host he is about to trust.
 *
 * "**The message names the provider and the host the link resolves to**, so a
 * swapped destination is visible before the tap rather than after the password."
 *
 * The host is READ OFF THE URL rather than stored beside it. The plan is explicit
 * that "a name that is hardcoded proves nothing" — a label that says
 * accounts.google.com while the link goes elsewhere is worse than no label,
 * because it is the reassurance a swap needs.
 */
export function handoffMessage(link: AuthLink, consolePath?: string): string {
  const host = new URL(link.url).host;
  const lines = [
    `${link.provider} needs you to sign in.`,
    `${link.url}`,
    `That opens ${host} — check it matches before you type anything.`,
  ];
  if (consolePath) lines.push(`It is waiting in the console too, under ${consolePath}.`);
  return lines.join("\n");
}

/** Has the provider's link died while he was not looking? */
export function linkIsFresh(link: AuthLink, now = new Date()): boolean {
  return link.expiresAt.getTime() > now.getTime();
}

/* ------------------------------------------------------------------ *
 * Parking, and what it releases.
 * ------------------------------------------------------------------ */

/**
 * Park a task waiting on him.
 *
 * "**Parking releases the lane.** A parked task is not running, and holding a
 * worker slot while waiting on a human turns a handful of unauthenticated
 * connections into a starved queue (ADR 007)."
 *
 * So the lease is cleared in the same statement that changes the state. Two
 * statements would leave a window in which the task is parked and still holding a
 * seat, and that window is exactly as long as whatever runs between them.
 */
export async function parkForAuth(
  pool: pg.Pool,
  args: { taskId: string; provider: string; now?: Date },
): Promise<void> {
  await pool.query(
    `UPDATE tasks
        SET state = 'waiting_for_user',
            lease_owner = NULL,
            lease_until = NULL,
            updated_at = $2
      WHERE id = $1`,
    [args.taskId, args.now ?? new Date()],
  );
}

export type ResumeOutcome =
  | { resumed: true; regenerated: boolean; why: string }
  | { resumed: false; why: string };

/**
 * He said he connected it, or the connection went healthy on its own.
 *
 * "Auth URLs expire. **A resume that replays a dead link resumes into a failure
 * that looks like Jarvis's fault.** On resume, check the link and regenerate
 * rather than replay."
 *
 * So the link is checked BEFORE the task is re-queued, and a dead one is minted
 * again from the flow — never replayed. `mint` is passed in rather than reached
 * for, because a resume for a flow that can no longer be regenerated has to be
 * able to say so instead of failing quietly.
 */
export async function resumeFromAuth(
  pool: pg.Pool,
  args: {
    taskId: string;
    link: AuthLink;
    /** Regenerates the link. Absent means this flow cannot be re-minted. */
    remint?: (() => AuthLink) | null;
    now?: Date;
  },
): Promise<ResumeOutcome> {
  const now = args.now ?? new Date();
  let regenerated = false;

  if (!linkIsFresh(args.link, now)) {
    if (!args.remint) {
      return {
        resumed: false,
        why: "the sign-in link expired and this flow cannot be regenerated — a fresh handoff is needed",
      };
    }
    args.remint();
    regenerated = true;
  }

  /*
   * Re-QUEUED, not set running. "Resume re-queues; it does not carry on in a seat
   * it never left" - the lane was released when it parked, and the scheduler
   * hands out seats.
   */
  const r = await pool.query<{ id: string }>(
    `UPDATE tasks SET state = 'queued', updated_at = $2
      WHERE id = $1 AND state = 'waiting_for_user'
      RETURNING id`,
    [args.taskId, now],
  );
  if (!r.rows[0]) return { resumed: false, why: "the task was not parked waiting for him" };

  return {
    resumed: true,
    regenerated,
    why: regenerated
      ? "the link had expired, so it was regenerated rather than replayed"
      : "resumed from where it stopped",
  };
}

/**
 * How many of this lane's seats are free.
 *
 * The plan says to "assert on lanes free, not on the parked tasks looking calm",
 * so the number is available to be asserted rather than inferred from task rows
 * that would look identical either way.
 */
export async function lanesInUse(pool: pg.Pool, lane: string): Promise<number> {
  const r = await pool.query<{ n: string }>(
    `SELECT count(*) AS n FROM tasks
      WHERE lane = $1 AND lease_owner IS NOT NULL`,
    [lane],
  );
  return Number(r.rows[0].n);
}
